workflows:
  android-release:
    name: Android Release AAB

    environment:
      flutter: stable
      vars:
        KEY_ALIAS: hiraku

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Restore keystore
        script: |
          set -e
          printf "%s" "$CM_KEYSTORE_B64" | base64 --decode > /tmp/hiraku-keystore.jks
          ls -l /tmp/hiraku-keystore.jks

      - name: Create key.properties (root)
        script: |
          set -e
          cat > key.properties << EOF
storePassword=$CM_KEYSTORE_PASSWORD
keyPassword=$CM_KEY_PASSWORD
keyAlias=$KEY_ALIAS
storeFile=/tmp/hiraku-keystore.jks
EOF
          # 確認（秘密は出さない）
          sed -E 's/(storePassword|keyPassword)=.*/\1=*** /' key.properties
          ls -l key.properties

      - name: Build AAB (release)
        script: |
          set -e
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/app/outputs/mapping/release/mapping.txt
