workflows:
  android-release:
    name: Android Release AAB

    environment:
      flutter: stable
      vars:
        KEY_ALIAS: hiraku

    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Restore keystore
        script: |
          set -e
          printf "%s" "$CM_KEYSTORE_B64" | base64 --decode > /tmp/hiraku-keystore.jks
          echo "Keystore restored:"
          ls -l /tmp/hiraku-keystore.jks

      - name: Verify keystore (readable + alias)
        script: |
          set -e
          echo "Verifying keystore readability..."
          keytool -list -keystore /tmp/hiraku-keystore.jks -storepass "$CM_KEYSTORE_PASSWORD" | head -n 50

      - name: Create key.properties (android + root)
        script: |
          set -e

          # Trim CR and leading/trailing spaces (do NOT print secrets)
          SP="$(printf "%s" "$CM_KEYSTORE_PASSWORD" | tr -d '\r' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
          KP="$(printf "%s" "$CM_KEY_PASSWORD"        | tr -d '\r' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"

          for f in android/key.properties key.properties; do
            cat > "$f" << EOF
storePassword=$SP
keyPassword=$KP
keyAlias=$KEY_ALIAS
storeFile=/tmp/hiraku-keystore.jks
EOF
            echo "Created $f"
            grep -nE '^storePassword=.+$' "$f"
            grep -nE '^keyPassword=.+$' "$f"
            sed -E 's/(storePassword|keyPassword)=.*/\1=***/' "$f"
            ls -l "$f"
          done

      - name: Gradle signingReport
        script: |
          set -e
          cd android
          ./gradlew :app:signingReport

      - name: Build AAB (release)
        script: |
          set -e
          flutter build appbundle --release

      - name: Verify AAB certificate (built artifact)
        script: |
          set -e
          echo "Verifying built AAB certificate..."
          ls -l build/app/outputs/bundle/release/app-release.aab
          keytool -printcert -jarfile build/app/outputs/bundle/release/app-release.aab | sed -n '1,35p'

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/app/outputs/mapping/release/mapping.txt
