workflows:
  android-release:
    name: Android Release AAB
    instance_type: linux
    environment:
      vars:
        KEY_ALIAS: hiraku
      flutter: stable
    scripts:
      - name: Flutter pub get
        script: flutter pub get

      # Codemagic上で android/key.properties を生成
      - name: Create android/key.properties
        script: |
          cat > android/key.properties << EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF

      - name: Build AAB (release)
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
